# Gradle properties
# Increase the heap size for the Gradle daemon
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8

# Increase memory for the Kotlin daemon
kotlin.daemon.jvmargs=-Xmx2g

# Enable parallel execution and build cache
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Android-specific properties
android.useAndroidX=true
android.nonTransitiveRClass=true
